spring.application.name=SistemaVentaVehiculos

# CONFIGURACIÓN CON VARIABLES DE ENTORNO
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-patient-sea-a4jcb8r4-pooler.us-east-1.aws.neon.tech:5432/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_lZIbm5tq0eGk}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET_KEY:miClaveSecretaSuperSeguraParaJWTQueDebeSerMuyLarga123456789012345678901234567890}
jwt.expiration=86400000